---
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - ansible/**/*
    - tmp/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*_spec.rb
Metrics/BlockLength:
  Exclude:
    - db/migrate/*
    - spec/**/*_spec.rb
    - spec/factories/**/*
    - spec/shared/**/*
    - Vagrantfile

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - db
    - to
    - id

Style/Documentation:
  Enabled: false
